// Generated by tools/build-pwa.mjs. A versioned app shell prevents mixed HTML/JS/WASM updates.
const PREFIX = 'dopa-drill-en-' + encodeURIComponent(new URL(self.registration.scope).pathname) + '-';
const CACHE = PREFIX + '5e44d76dd3e328cd';
const ASSETS = [
  "./",
  "./LICENSE.txt",
  "./fonts/OFL-DelaGothicOne.txt",
  "./fonts/OFL-ZenMaruGothic.txt",
  "./fonts/dela-gothic-one.woff2",
  "./fonts/zen-maru-gothic-black.woff2",
  "./fonts/zen-maru-gothic-bold.woff2",
  "./icon.svg",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-square.svg",
  "./index.html",
  "./js/audio.js",
  "./js/bg.js",
  "./js/core.js",
  "./js/dopakichi.js",
  "./js/fx.js",
  "./js/growth.js",
  "./js/guide.js",
  "./js/main.js",
  "./js/math-core.js",
  "./js/problems.js",
  "./js/pwa.js",
  "./js/quests.js",
  "./js/scoring.js",
  "./js/session.js",
  "./js/skills.js",
  "./js/store.js",
  "./js/trophies.js",
  "./js/unlocks.js",
  "./manifest.webmanifest",
  "./style.css",
  "./wasm/dopa_core.wasm"
];
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS))));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith(PREFIX) && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const scope = new URL(self.registration.scope);
    const isShell = event.request.mode === 'navigate' && (url.pathname === scope.pathname || url.pathname === scope.pathname + 'index.html');
    const request = isShell ? new URL('./', self.registration.scope).href : event.request;
    return await cache.match(request) || fetch(event.request);
  }));
});
