import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
const root = resolve('app');
async function files(dir = '') {
  const list = [];
  for (const e of await readdir(resolve(root, dir), { withFileTypes: true })) {
    const p = dir ? `${dir}/${e.name}` : e.name;
    if (e.isDirectory()) list.push(...await files(p));
    else if (p !== 'sw.js' && !p.startsWith('_') && !p.startsWith('.')) list.push(p);
  }
  return list;
}
const assets = (await files()).sort();
const hash = createHash('sha256');
for (const p of assets) hash.update(p).update(await readFile(resolve(root, p)));
const version = hash.digest('hex').slice(0, 16);
const body = `// Generated by tools/build-pwa.mjs. A versioned app shell prevents mixed HTML/JS/WASM updates.
const PREFIX = 'dopa-drill-en-' + encodeURIComponent(new URL(self.registration.scope).pathname) + '-';
const CACHE = PREFIX + '${version}';
const ASSETS = ${JSON.stringify(['./', ...assets.map(p => './' + p)], null, 2)};
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS))));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith(PREFIX) && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const scope = new URL(self.registration.scope);
    const isShell = event.request.mode === 'navigate' && (url.pathname === scope.pathname || url.pathname === scope.pathname + 'index.html');
    const request = isShell ? new URL('./', self.registration.scope).href : event.request;
    return await cache.match(request) || fetch(event.request);
  }));
});
`;
await writeFile(resolve(root, 'sw.js'), body);
console.log(`PWA cache ${version}: ${assets.length} local files`);
